# Generated by Django 5.0.7 on 2024-07-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Poupança'), ('INVEST', 'Investimentos'), ('OTHER', 'Outros')], default='OTHER', max_length=20),
        ),
    ]
