# Generated by Django 5.0.7 on 2024-07-31 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_account_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('AMEX', 'American Express'), ('DISCOVER', 'Discover'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Tipo de Cartão')),
                ('card_number', models.CharField(max_length=19, verbose_name='Número do Cartão')),
                ('cardholder_name', models.CharField(max_length=100, verbose_name='Nome do Titular')),
                ('expiration_date', models.DateField(verbose_name='Data de Validade')),
                ('security_code', models.CharField(max_length=4, verbose_name='Código de Segurança (CVV)')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor da transação'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=50, verbose_name='Nome para a conta'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Poupança'), ('DIGITAL', 'Conta Digital'), ('INVEST', 'Investimentos'), ('OTHER', 'Outros')], default='OTHER', max_length=20, verbose_name='Tipo de Conta'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balanço'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('FOOD', 'Alimentação'), ('TRANSPORT', 'Transporte'), ('HOUSING', 'Moradia'), ('HEALTH', 'Saúde'), ('EDUCATION', 'Educação'), ('ENTERTAINMENT', 'Lazer e Entretenimento'), ('SHOPPING', 'Compras'), ('PERSONAL', 'Despesas Pessoais'), ('FINANCE', 'Finanças'), ('OTHER', 'Outros'), ('SALARY', 'Salário'), ('FREELANCE', 'Freelance'), ('RENTAL', 'Aluguéis'), ('INVESTMENTS', 'Investimentos'), ('GIFTS', 'Presentes'), ('SALES', 'Venda de Itens'), ('REIMBURSEMENTS', 'Reembolsos')], max_length=50, verbose_name='Nome da categoria'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account', verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data em que foi realizado a transação'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEBIT', 'Débito'), ('CREDIT', 'Crédito')], max_length=10, verbose_name='Tipo de Transação'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor atual')),
                ('targeted_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Almejado')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(verbose_name='Data final para meta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
