# Generated by Django 5.0.7 on 2024-07-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_creditcard_remove_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Alimentação'), ('TRANSPORT', 'Transporte'), ('HOUSING', 'Moradia'), ('HEALTH', 'Saúde'), ('EDUCATION', 'Educação'), ('ENTERTAINMENT', 'Lazer e Entretenimento'), ('SHOPPING', 'Compras'), ('PERSONAL', 'Despesas Pessoais'), ('FINANCE', 'Finanças'), ('OTHER', 'Outros'), ('SALARY', 'Salário'), ('FREELANCE', 'Freelance'), ('RENTAL', 'Aluguéis'), ('INVESTMENTS', 'Investimentos'), ('GIFTS', 'Presentes'), ('SALES', 'Venda de Itens'), ('REIMBURSEMENTS', 'Reembolsos')], default='OTHER', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Alimentação'), ('TRANSPORT', 'Transporte'), ('HOUSING', 'Moradia'), ('HEALTH', 'Saúde'), ('EDUCATION', 'Educação'), ('ENTERTAINMENT', 'Lazer e Entretenimento'), ('SHOPPING', 'Compras'), ('PERSONAL', 'Despesas Pessoais'), ('FINANCE', 'Finanças'), ('OTHER', 'Outros'), ('SALARY', 'Salário'), ('FREELANCE', 'Freelance'), ('RENTAL', 'Aluguéis'), ('INVESTMENTS', 'Investimentos'), ('GIFTS', 'Presentes'), ('SALES', 'Venda de Itens'), ('REIMBURSEMENTS', 'Reembolsos')], default='OTHER', max_length=20, verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
