# Generated by Django 5.0.7 on 2024-08-01 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_creditcard_surname_creditcard_user_transaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
